[package]
name = "jdn-echo"
version = "0.1.0"
authors = ["eta077 <eta077@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jdn-cli = { git = "https://github.com/eta077/jdn-cli", tag = "v0.1.1" }
